---
title: "Literature Review"
name: "Dasia McClinton"
format: html
editor: visual
---

## Goal

The purpose of this paper is to discuss and critically evaluate the use of LMMs in dealing with the numerous challenges associated with hierarchical data, missing data, and understanding fixed and random effects in correlated information structures. The review will focus on explaining how exactly LMMs have been used or can be applied at best and where precisely the usage of LMMs will provide better results over traditional linear models, which assume independence of observations that are often violated in nested or clustered samples. By examining key sources, including foundational and contemporary works by Bates, Bolker, Fox, McCulloch, Meteyard, Davies, and Starkweather, the paper seeks to highlight how LMMs offer a robust statistical framework for dealing with the challenges of real-world data. This includes their ability to estimate within-group correlations with random effects, their ability to handle missing data under the MAR mechanism, and the fact that they are well suited for fixed effects at the population level and random effects at the group and individual levels. Consequently, the review strives to show that despite the challenges posed by LMMs in identical and diverse datasets, these models are essential in generating more precise and correct approximations in various sub-disciplinary areas of ecological, psychological, and social science research. Furthermore, the review stresses the need to correctly model the random effects structure properly in order to obtain an accurate estimate and correct inference, hence the call for the continued use as well as advancement of LMMs as a standard method for analysis of hierarchical and correlated data.

## Importance

A significant facet of using LMMs is the modeling issue of real-world data, which involves storing data structures, missing data, and correlated data, issues that ordinary linear models cannot solve effectively. In hierarchical data, observations again lie in clusters, which means the error terms of observations in the same cluster are often correlated, which is a violation of the assumption of independence that underpins most traditional linear models. It may result in bias in the estimates and wrong inferences and lead to high Type I error rates. Bates (2014) points out that LMMs play a crucial role in analyzing such structures through the addition of random effects that effectively capture the covariance within groups and, subsequently, the unequal variability within a group. In the same manner, Bolker (2015) states that LMMs are helpful in ecological statistics since data is repeatedly collected from different sites or at different times, which results in complicated, correlated data. The flexibility offered by LMMs to accommodate random intercepts and slopes positively impacts generalization across groups/individuals and provides better estimates and corresponding inferences.

Another important field where LMMs are crucial is the issue of missing data management. Missing data is intrinsic to longitudinal and repeated measures studies arising from participant attrition or incomplete assessments. In particular, listwise deletion and mean imputation are known to result in biased estimates and decrease statistical power. Meteyard and Davies (2020) recommend using LMMs because such methods allow working with missing data under the premise of Missing at Random (MAR), using all the available information without having to exclude cases with missing values. In addition, LMMs model the correlation structure of the data and offer more accurate estimates by correcting the uncertainty due to failure than other methods. Starkweather (2010) builds on this by presenting the characteristics of LMMs in further detail and how well they are able to handle cases of different numbers of observations across participants, which is ideal in unbalanced designs. This robustness is especially helpful in areas like psychology, analysis of ecosystems, and other social sciences where data is likely to be missing. Therefore, the use of LMMs in cases of incomplete data is highly relevant to modern statistical analysis as they provide general and valid estimates of the data, thus improving the researcher's conclusiveness.

## Methods

Linear Mixed Models (LMMs) address the issues of hierarchical data by adding fixed and random effects in the model, making it possible to model nested data properly. As with fixed effects, the random effects describe the general population trends, while the random effects will measure the variability of one group or cluster compared to another, for instance, variability between individuals or study centers. According to Bates (2014), the use of LMMs permits the random intercepts and slopes that would fit variations at the different levels in the hierarchy to facilitate the modeling of the correlation within groups. This dual structure guarantees that, in the analysis process, the reliance on observations within the same group is taken into account. Consequently, the parameter rates estimated are more reliable and free from biases that could be realized when data is treated as independent. Besides, the LMMs can be used to provide efficient methods of dealing with missing data, which is a typical problem in the context of BLP (McCulloch, 1996). Listwise deletion and mean imputation procedures are not efficient and can lead to bias because they do not make proper use of the information and do not cope with the variance due to the missing values. LMMs, on the other hand, are purposefully developed to deal with missing data under the ability of Missing at Random (MAR). According to Meteyard and Davies (2020), LMMs utilize maximum likelihood estimation (MLE) or restricted maximum likelihood estimation (REML) to accord all of the available data, including incomplete cases, in the model. Besides, LMMs eliminate the problem of analyzing the coefficients with interaction fixed and random effects by articulating how variations of the population level reflect the groups' level changes. According to Fox (2002), the researcher needs to have a clear understanding of the concepts of fixed and random effects for comparison while specifying and estimating the models. The fixed effects extend the results of the linearity identified in the whole population regarding the objects under analysis to all interested parties, while the random effects control deviations from this line within distinct groups.

## Results/Limitations

The literature supports that Linear Mixed Models (LMMs) offer a versatile method for analyzing complex and nested observational structures that involve missing data and both fixed and random effects. LMMs perform exceptionally well with nested or clustered structures since they are inherently capable of handling random effects that capture within-cluster dependency while ensuring one does not fall for biases associated with traditional linear models. Bates (2014) and Bolker (2015) state that this capability improves the precision of the point estimates as well as the efficiency of inference in research areas where hierarchical data are frequent. Besides, the LMMs have the capability of utilizing all available information and addressing the uncertainty that results from missing data. For instance, Meteyard and Davies (2020) provided a clear account of how estimates obtained from maximum likelihood or restricted maximum likelihood estimation in LMMs are less biased as compared to those based on listwise deletion.

However, the following are some of the limitations associated with LMMs. LMMs are rather complex as opposed to GLMMs, the specification of which and their interpretation might be problematic in some cases. The specification of random effects is critical; a poorly stipulated model may complicate or weaken the study's results and efficiency. According to McCulloch (1996), failure to define or model random effects correctly can hide the actual fixed effects, which in turn complicates the interpretation. Moreover, since LMMs involve numerous computations, they could be computationally costly, mainly when applied to big data or when the models we want to fit contain numerous parameters, which can present practical difficulties to the researchers. According to Starkweather (2010), although LMMs are flexible in terms of analyzing complex designs, their computational requirements and the necessity of selecting proper tuning parameters may pose a challenge to some researchers, thus making them less user-friendly. Nevertheless, based on the literature review, the primary conclusion is that LMMs are an essential development in statistical modeling, providing optimal solutions to multiple data analysis problems.

**References**

Bates, D. (2014). Fitting linear mixed-effects models using lme4. *arXiv preprint arXiv:1406.5823*.

Bolker, B. M. (2015). Linear and generalized linear mixed models. *Ecological statistics: contemporary theory and application*, 309-333.

Fox, J. (2002). *An R and S-Plus companion to applied regression*. Sage.

McCulloch, C. E. (1996). An introduction to generalized linear mixed models.

Meteyard, L., & Davies, R. A. (2020). Best practice guidance for linear mixed-effects models in psychological science. *Journal of Memory and Language*, *112*, 104092.

Starkweather, J. (2010). Linear mixed effects modeling using R. *Unpublished Manuscript*
